### ISSUE TITLE
How to get the new item added in another Todoist client?

### ISSUE THREAD

**Issue by LingForCC** [Cosmitar/todoist-js#2]
If I create an app with this sdk and add an item in another Todoist client, say mobile client, how can the app knows that there is an item created? It seems that the only way is to use polling at the moment.

**Comment by Cosmitar** [comment]
Apparently there is an approach provided by Todoist. You need to configure your app from the [App Management Console](https://developer.todoist.com/appconsole.html) with a [webhook](https://developer.todoist.com/#webhooks) url pointing to your server. This way you'll receive real-time notifications from your app user actions. That server should be linked to your javascript app by a [websocket](https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API), then the server can push a notification to the browser and the javascript app can sync data by using this client.

**Comment by LingForCC** [comment]
That makes sense.
