### ISSUE TITLE
How do you know what options there are?

### ISSUE THREAD

**Issue by mvaneijgen** [Cosmitar/todoist-js#5]
I am building a wish list app and wanted to use a todo app as my data. (first tried Wunderlist, but because Microsoft bought it, it is now death. Let's hope they don't do the same thing with this platform)

I found your [demo project](https://github.com/fusenlabs/asist) and am spitting that one out to see what you use. I found changing `.completed.get_stats()` to `.query(['today'])` gets me all items in the Today view. This helped me find my list ID (wish list ID, which is `2187923865`) and now I want to query only that list, but I don't see any options. 

Is there a list of all the possible options. The default Todoist API is no help either.

**Comment by Cosmitar** [comment]
Same question was asked in the official Todoist repo https://github.com/Doist/todoist-python/issues/37
The short answer:
```
DEPRECATED: query endpoint is deprecated for a long time and this
        method will be removed in the next major version of todoist-python
```
You should `sync` and filter items into your code. Is it the best option? probably not.

They also have a REST API 🎉 under development, still in beta: https://developer.todoist.com/rest/v8

**Comment by mvaneijgen** [comment]
Thanks for pointing out the REST API, that seems much easier. I'll check it out. I just want to use something like Axios with Vue to render some todo's on a webpage.

**Comment by mvaneijgen** [comment]
@Cosmitar thanks again, the REST API is exactly what I need and seems much easier than the rest. I already got all my todos render on the page! 

If anyone else is looking to get something similar done, here is my Axios code for Vue.js 

https://gist.github.com/mvaneijgen/dad0b500c53b8d188c93dde4a6c71d9b
